version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    # environment:
    #   - MONGO_URI=mongodb://admin:password@mongodb:27017/mydatabase  # Updated with credentials

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root # Root username
      - MONGO_INITDB_ROOT_PASSWORD=supersecret  # Root password
      # - MONGO_INITDB_DATABASE=mydatabase  # Default database

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=supersecret
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_DEBUG=true
      - ME_CONFIG_MONGODB_AUTH_MECHANISM=SCRAM-SHA-256
    depends_on:
      - mongodb
   

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:
