version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGO_ADMINPASSWORD=password
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend  # Assuming your frontend Dockerfile is in the 'frontend' folder
    container_name: frontend
    ports:
      - "80:80"  # Exposing port 80
    depends_on:
      - backend  # If your frontend depends on the backend to be up

volumes:
  mongo-data:
